### ISSUE TITLE
very curious about how good about the accuracy without fine-tuning pruned network

### ISSUE THREAD

**Issue by pecanjk** [liuzechun/MetaPruning#11]
I'm very curious about how good about the accuracy without fine-tuning the pruned network. It  may be not as good as directly trained network. If not the best prediction from Pruning network. Maybe you can not make sure the searched results are the best

**Comment by liuzechun** [comment]
Hi, I think there is no guarantee in 'best' even with fine-tuning. With meta-learning, we find even without fine-tuning, it is almost very satisfied for predicting good-preforming pruned networks. Fine-tuning is too time costly.
