### ISSUE TITLE
The accuracy of the PruningNet

### ISSUE THREAD

**Issue by Stoneplay** [liuzechun/MetaPruning#14]
Hi, though I have implemented the accuracy of the pruned network in the paper, I found that the performance of  pruning net trained in the first stage is not well. Combining the results of the following two stages, the better the pruning net is, the higher the accuracy of pruned network is. 
Could you please share your accuracy of pruning net?

**Comment by liuzechun** [comment]
Hi, the accuracy of pruning net is around 50%. As long as the PruningNet can give us a reliable accuracy ranking of different Pruned network structures, it don't need to be as high as the retrained individual Pruned networks.
