### ISSUE TITLE
BN Stat Params during searching

### ISSUE THREAD

**Issue by zx33** [liuzechun/MetaPruning#15]
Hello, I really like this work of network pruning.

I have a little problem about the BN's parameters during searching.

Take MobileNetV1 as an example, while training the PruningNet, BN's running_mean/vars have already been calculated and saved, why not directly use these values, but recalibrate them during searching?

**Comment by bestfleer** [comment]
The in channels of each bn layer is not same in training so that its running mean and running var can not be recorded correctly. The details for this situation are introduced in paper Slimmable Networks.

**Comment by zx33** [comment]
> The in channels of each bn layer is not same in training so that its running mean and running var can not be recorded correctly. The details for this situation are introduced in paper Slimmable Networks.

But the PruningNet has created and updated BN's for each channel scale opts:
```
self.first_bn = nn.ModuleList()
for oup_scale in channel_scale:
     oup = int(self.base_oup * oup_scale)
     self.first_bn.append(nn.BatchNorm2d(oup))
```

Does this specific BNs for each scale opts still has the problem?

**Comment by zeyu-liu** [comment]
> > The in channels of each bn layer is not same in training so that its running mean and running var can not be recorded correctly. The details for this situation are introduced in paper Slimmable Networks.
> 
> But the PruningNet has created and updated BN's for each channel scale opts:
> 
> ```
> self.first_bn = nn.ModuleList()
> for oup_scale in channel_scale:
>      oup = int(self.base_oup * oup_scale)
>      self.first_bn.append(nn.BatchNorm2d(oup))
> ```
> 
> Does this specific BNs for each scale opts still has the problem?

During training PruningNet, each specific path is randomly selected on each node. So, the input activation with same size of this block may have different distribution caused by the difference in previous nodes.

For example, path1 = [1 7 2 5 8 3 ...], path2 = [2 1 9 6 5 3 ...], the BN blocks in node '3' have same 
 size, but may have different 'mean' / 'variance' distribution.

**Comment by zx33** [comment]
> > > The in channels of each bn layer is not same in training so that its running mean and running var can not be recorded correctly. The details for this situation are introduced in paper Slimmable Networks.
> > 
> > 
> > But the PruningNet has created and updated BN's for each channel scale opts:
> > ```
> > self.first_bn = nn.ModuleList()
> > for oup_scale in channel_scale:
> >      oup = int(self.base_oup * oup_scale)
> >      self.first_bn.append(nn.BatchNorm2d(oup))
> > ```
> > 
> > 
> > Does this specific BNs for each scale opts still has the problem?
> 
> During training PruningNet, each specific path is randomly selected on each node. So, the input activation with same size of this block may have different distribution caused by the difference in previous nodes.
> 
> For example, path1 = [1 7 2 5 8 3 ...], path2 = [2 1 9 6 5 3 ...], the BN blocks in node '3' have same
> size, but may have different 'mean' / 'variance' distribution.

Oh, I see, thank you for the explanation.
