### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Zeitzmz** [liuzechun/MetaPruning#2]
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    main()
  File "train.py", line 63, in main
    model = nn.DataParallel(model).cuda()
  File "/home/abc/anaconda3/envs/torch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/abc/anaconda3/envs/torch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/abc/anaconda3/envs/torch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/abc/anaconda3/envs/torch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/abc/anaconda3/envs/torch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/home/abc/anaconda3/envs/torch1.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 11.78 GiB total capacity; 281.29 MiB already allocated; 29.56 MiB free; 18.71 MiB cached)

Do you meet this problem

**Comment by liuzechun** [comment]
I use 8 1080Ti GPUs. If you use fewer GPUs than that, you can decrease the batch-size. Just make sure you also decrease the initial learning rate with the same ratio as batch-size.

**Comment by Zeitzmz** [comment]
> I use 8 1080Ti GPUs. If you use fewer GPUs than that, you can decrease the batch-size. Just make sure you also decrease the initial learning rate with the same ratio as batch-size.

I use 8 1080Ti GPUS too. When I decrease batch-size to 8, the error still exist. There maybe something wrong with my torch.

1、Will you release you search results?
2、How do you train your search results from scratch? like batch-size, total epochs, leanring rate, weight-decay and so on.
I train mobilenetV2-1x(flops: 300.7M, same with tensorflow), get top-1: 73%, batch-size=256, total epoch: 300 epoch, learning rate: 0.1(consine decay to 0.0001), weight decay: 4e-5.  tensorflow official results is top1 72%. I find many paper show mobilenetV2-1x top1: 72% too. Do you train mobilenetV2 by yourself?
Thank you very much.

**Comment by liuzechun** [comment]
> > I use 8 1080Ti GPUs. If you use fewer GPUs than that, you can decrease the batch-size. Just make sure you also decrease the initial learning rate with the same ratio as batch-size.
> 
> I use 8 1080Ti GPUS too. When I decrease batch-size to 8, the error still exist. There maybe something wrong with my torch.
> 
> 1、Will you release you search results?
> 2、How do you train your search results from scratch? like batch-size, total epochs, leanring rate, weight-decay and so on.
> I train mobilenetV2-1x(flops: 300.7M, same with tensorflow), get top-1: 73%, batch-size=256, total epoch: 300 epoch, learning rate: 0.1(consine decay to 0.0001), weight decay: 4e-5. tensorflow official results is top1 72%. I find many paper show mobilenetV2-1x top1: 72% too. Do you train mobilenetV2 by yourself?
> Thank you very much.

1. I released my search results, it is in the models part. You can download the models as well as the corresponding network structure by clicking the download link.
2. I use batchsize = 1024, total epoch: 256 learning_rate : 0.5( linear decay to 0) weight decay 4e-5. Just as the default value in the evaluation code. I think there could be some deviation in the results if you use more advanced training scheme and which will also yields accuracy enhancement in accuracy of the searched model.

**Comment by ccsone** [comment]
hello   how do you   use  8 1080ti gpu?  it needs add new codes  for useing  it? i use os.environ....=[0,1,2,3]    it doesn't work.  @Zeitzmz
