### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by TerryLoveMl** [liuzechun/MetaPruning#21]
Thank you for you interesting work. When i run the resnet code,the error appears in the below. I try to adjust the batchsize, but it does not work. any  idea about this? 
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 6.31 GiB already allocated; 8.02 MiB free; 32.19 MiB cached)

**Comment by liuzechun** [comment]
Hi, Thanks for your interest in my work. I use 8 1080Ti GPUs. If you use fewer GPUs than that, you can decrease the batch-size. Just make sure you also decrease the initial learning rate with the same ratio as batch-size. You can also refer to issue #2 ~
