### ISSUE TITLE
RuntimeError: Given input size: (1280x1x1). Calculated output size: (1280x0x0). Output size is too small

### ISSUE THREAD

**Issue by cvJie** [liuzechun/MetaPruning#22]
hi，
 I  changed the imagenet to pycifar10( classes=10).
now, I edit the mobilenet_v2.py the classes =10,and run the mobilenetb2--train,
error is:
RuntimeError: Given input size: (1280x1x1). Calculated output size: (1280x0x0). Output size is too small

why, and how to solve it ,thanks

**Comment by liuzechun** [comment]
Hi, did you solve that? sorry I am too busy these days and I just got some time to reply the issues.
