### ISSUE TITLE
Integrate constraint into genetic algorithm

### ISSUE THREAD

**Issue by zzqiuzz** [liuzechun/MetaPruning#24]
Hi! If one wants to prune a CNN model with  pruning ratio set as 0.4 using genetic algorithm,then how to apply this constraint within GA?  I have no idea if to modify pop initialization or fitness function.Also cross/mutate operations will do impacts on pruning ratio.

**Comment by liuzechun** [comment]
Hi, we just calculate the FLOPs/ latency of each gene (after the random/mutation/crossover operation on the pruning ratio), and simply remove the gene that exceeds our constraint to make sure all the genes in the population satisfy the constraint.
