### ISSUE TITLE
where  can  i change  the pruning Ratio  ?

### ISSUE THREAD

**Issue by ccsone** [liuzechun/MetaPruning#26]
I have finished the three steps of meta-pruning  Net,using my dataset. But i didn't find the place where the pruning ratio  changes to evaluate the result of meta-pruning net, thanks  for your help

**Comment by ccsone** [comment]
is it used by FLOPS?

**Comment by liuzechun** [comment]
Hi, thanks for your interest in my work, sorry for my late reply. Did you already solved that?
