### ISSUE TITLE
Why random the "scale_ids" in every batch 

### ISSUE THREAD

**Issue by canteen-man** [liuzechun/MetaPruning#29]
train.py 
175 line, random the scale which means the model in every layer need hold the number of channels.
And I find every batch random once. 
If every batch random once,how to know which number of channels is the best combination in the model.
In a epoch,there are many batchs and it will random scales many times.

**Comment by canteen-man** [comment]
@liuzechun ,looking forward to your reply，thank you.

**Comment by liuzechun** [comment]
Hi, thanks for your interest in my work.
Indeed, this is a very good question. For training the pruning net, our aim is not to find the best combination, but to equally train the weights for all the possible combinations. Such that in the search time, we can compare the goodness of each combination with a fairness in the equally-trained weights. By using the random sampling, we can let the pruningnet to see different combinations, and learn to generate weights for them, then we can use those weights for evaluating the model at the search time. We only compare the goodness of the model at search time. Is my explanation clear?
