### ISSUE TITLE
Model tar  decompression error

### ISSUE THREAD

**Issue by zyc4me** [liuzechun/MetaPruning#3]
下载提供的预训练模型，解压时出错

**Comment by liuzechun0216** [comment]
May I know what kind of error you encountered? I use the iZip to compress the file and I am using the mac. I'm not sure whether that could be problematic if you are using windows

**Comment by liuzechun** [comment]
May I know what kind of error you encountered? I use the iZip to compress the file and I am using the mac. I'm not sure whether that could be problematic if you are using windows
