### ISSUE TITLE
Problems in searching and evaluating stage

### ISSUE THREAD

**Issue by ZhanHuaa** [liuzechun/MetaPruning#31]
Hi, I really appreciate this work and want to reproduce paper result. But there exists two problems in my experiment.
First, as mentioned in the paper, the searching process only costs a few seconds, but i ran it over one day and did not have result... So i wonder is there any available searching results (may be a model architecture vector)  corresponding to the paper result, even one result on ResNet50 will be fine.
Second, as mentioned in README.md, "By simply copying the encoding vector to the rngs = [ ] in evaluate.py, you can evaluate the Pruned Network corresponding to this encoding vector." , but i can not find "rngs = [ ]" in evaluate.py, and can not run it. 
By the way, the ResNet-50 model you provided on One-drive is over-sized and can not be downloaded. Can you provide it by other way.
Looking forward to your reply, Chinese will be fine~

**Comment by liuzechun** [comment]
Thank you for your interest in my work. The rngs are defined in the models, when you download the model, there will be rngs inside the corresponding resnet.py file.
