### ISSUE TITLE
Failed to reproduce MobileNet-v2 results (eval)

### ISSUE THREAD

**Issue by haolibai** [liuzechun/MetaPruning#32]
Hi, thanks for your inspiring work and published code. 

I have encountered a problem reproducing the results for MobilNet-v2 140M. I directly download the script of MobileNet-140M and use the default parameter setting in the script, but just got the accuracy of Top-1 Acc: 67.40%, Top-5 Acc: 87.47%. (The reported Top-1 Acc is 68.2% in the paper).

May I know if you use the default parameter setting in the script to obtain the results of MobileNet-v2?

Thanks.

**Comment by liuzechun** [comment]
Hi, thanks for your interest in my work. 
Did you use the 140M_mobilenet_v2.py file downloaded from the OneDrive Link? The channel ids should be as follows:
overall_channel_ids = [2,  3,  4,  4,  7,  7,  7, 10, 10, 10, 10,  5,  5,  5, 12, 12, 12,  7]
mid_channel_ids = [11, 11,  6, 15,  8, 13, 16, 14,  3, 14, 10, 17, 13, 17, 17, 17, 16]
Thanks

**Comment by haolibai** [comment]
Yes I use the one from OneDrive. 
May I know whether the default parameter setting in the script "mobilenet_v2.py" is used to reproduce the results in the paper? Thanks!

**Comment by liuzechun** [comment]
Yes, I just double checked the hyperparameter settings. The default parameter setting in the script "mobilenet_v2.py"  and "evaluation.py" are the parameters I used in the experiments.

**Comment by haolibai** [comment]
Thanks for your reply. That's a bit strange. Let me double check my run.
