### ISSUE TITLE
How to evaluate mobilenet v2 with a new dataset?

### ISSUE THREAD

**Issue by XiangqianMa** [liuzechun/MetaPruning#36]
Thanks for your work!
I have trained mobilenet v2 with my own dataset. Untile now, I have finished training step and search step. But when I tried to execute the evaluate step, I couldn't find 'rngs' in `evaluate.py`. So, can you describe more details of the evaluate step. 
Waiting for your reply!

**Comment by liuzechun** [comment]
Hi, thanks for your interest in our work!
After searching is done, the top1 rngs will be shown in the log file of the search phase. You need to manually copy the rngs to the rngs = [ ] in evaluate.py
