### ISSUE TITLE
Where to find the following tow parameters in mobilenetv2.py?

### ISSUE THREAD

**Issue by XiangqianMa** [liuzechun/MetaPruning#37]
To evaluate mobilenetv2 in my dataset, I don't know where to find the following tow parameters.
```python
overall_channel_ids = [14, 12, 11, 11, 8, 8, 8, 7, 7, 7, 7, 8, 8, 8, 14, 14, 14, 8]
mid_channel_ids = [6, 5, 2, 15, 7, 17, 14, 5, 11, 12, 12, 11, 6, 16, 14, 13, 14]
```
After the search step, I got the following files in the search directory:
![Screenshot from 2020-10-17 12-20-11](https://user-images.githubusercontent.com/16034094/96328236-361bb100-1073-11eb-8507-bf32d5ee76af.png)
Waiting for your reply!

**Comment by liuzechun** [comment]
You can find it in these two log files. At the end of these file, it will print the top-1 rngs.
![未命名](https://user-images.githubusercontent.com/26427257/96475746-5fb71280-1202-11eb-8771-cd40925d86eb.png)
