### ISSUE TITLE
Why the accuracy is low  in the start of training  about mobilenetV2 part?

### ISSUE THREAD

**Issue by YANGWAGN** [liuzechun/MetaPruning#5]
During the training, I only changed the batch size from the default 512 to 256, but the Acc@1 is only about 5% and the Acc@5 is only about 15% before the 5th epoch. Do you encounter this situation during the training?  Thank you !

**Comment by liuzechun** [comment]
Low training accuracy is absolutely normal in training the PruningNet. We also experienced that. Thinking that the PruningNet need to predict weights for various different Pruned Networks while the weight in a normal network only need to suit themselves to a single network, it is understandable for PruningNet achieving not as high accuracy as we expect for a normal network.

**Comment by liuzechun** [comment]
Low training accuracy is absolutely normal in training the PruningNet. We also experienced that. Thinking that the PruningNet need to predict weights for various different Pruned Networks while the weight in a normal network only need to suit themselves to a single network, it is understandable for PruningNet to achieve not as high accuracy as we expect for a normal network

**Comment by liuzechun** [comment]
Low training accuracy is absolutely normal in training the PruningNet. We also experienced that. Thinking that the PruningNet need to predict weights for various different Pruned Networks while the weight in a normal network only need to suit themselves to a single network, it is understandable for PruningNet achieving not as high accuracy as we expect for a normal network.
