### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by he-y** [liuzechun/MetaPruning#6]
Thanks for the great work. 
I have a question about the data augmentation method.

I notice that  `RandomResizedCrop(224, scale=(crop_scale, 1.0)), Lighting(lighting_param),` are used, which is different from [pytorch official data augmentation](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L200-L207).

What is the gap between these two data augmentation methods?
Thanks.

**Comment by liuzechun** [comment]
Thanks for your interest in my work.
Not much difference I think, but I didn't try the original one. Because this data augmentation is similar with the ShuffleNet and I think is widely adopted in many studies.
